<?php

/**
 * ============================================================
 *  catalogo.php — Catálogo de categorias e produtos
 * ------------------------------------------------------------
 *  Lista de nomes tal como fornecida pelo cliente. Só nomes:
 *  os slugs, preços, descrições e imagens são derivados no
 *  seed (database/seed_catalogo.php).
 *
 *  Vários produtos aparecem em mais do que uma categoria. Como
 *  a tabela `products` só admite uma categoria por produto, o
 *  seed atribui cada nome à categoria de maior prioridade em
 *  que aparece (ver PRIORIDADE_CATEGORIAS mais abaixo).
 * ============================================================
 */

declare(strict_types=1);

/**
 * Categorias na ordem em que devem aparecer, com os respectivos produtos.
 *
 * @return array<string,array{nome:string,descricao:string,fotos:string[],produtos:string[]}>
 */
function catalogo_categorias(): array
{
    return [
        'papelaria-personalizada' => [
            'nome'      => 'Papelaria Personalizada',
            'descricao' => 'Cartões, flyers, convites, blocos e toda a papelaria da sua marca.',
            'fotos'     => ['1611532736579-6b16e2b50449', '1586281380349-632531db7ed4', '1519791883288-dc8bd696e667', '1524234107056-1c1f48f64ab8'],
            'produtos'  => [
                'Flyer', 'Cartão de Visita', 'Pasta Personalizada', 'Folder 1 Dobra', 'Tag Personalizada',
                'Envelope Personalizado', 'Panfleto', 'Papel Timbrado', 'Receituário', 'Calendário de Mesa 2027',
                'Agenda Personalizada 2027', 'Bloco de Notas Personalizado', 'Cartaz', 'Marca-Página',
                'Cartão de Visita Hot Stamping', 'Bloco de Notas com Capa Blocado', 'Flyer Hot Stamping',
                'Bloco para Rascunho', 'Bloco de Notas com Capa Wire-o', 'Flyer Premium', 'Tag Econômica',
                'Credencial', 'Cartão de Agradecimento Personalizado', 'Tag Hot Stamping', 'Cardápio de Papel',
                'Caderno Personalizado', 'Agenda Permanente', 'Pasta Hot Stamping', 'Convite',
                'Caderno Pequeno Personalizado com Capa Impressa', 'Caderneta Pequena', 'Caderneta Grande',
                'Caderneta Capa Impressa', 'Convite de Casamento', 'Convite de Casamento Hot Stamping',
                'Envelope de Segurança Papel', 'Mini Calendário de Mesa 2027', 'Calendário de Parede Básico 2027',
                'Planner Semanal', 'Pasta Verniz', 'Papel Embrulho para Presente',
                'Calendário de Parede Premium 2027', 'Envelope de Segurança Cartão', 'Pasta Markatto',
                'Caderno com Caneta', 'Convite Hot Stamping', 'Tag para Roupas', 'Porta Cartão Chave para Hotel',
                'Tag Verniz', 'Cartão de Visita Ultra Grosso', 'Cartão de Agradecimento Hot Stamping',
                'Tag para Ovo de Páscoa', 'Cartão de Páscoa Personalizado', 'Cartão Postal Hot Stamping',
                'Régua de Papel', 'Santinho Personalizado', 'Folder 1 Dobra Econômico',
                'Cartão de Visita com Verniz', 'Caderno de Desenho Capa Impressa', 'Folha de Máquina',
                'Caderneta com Caneta Personalizado', 'Tag Premium', 'Convite de Casamento Markatto', 'Recibo',
                'Cartão Vale Presente Personalizado', 'Cartão Vale Presente Hot Stamping',
                'Calendário de Mesa Premium 2027', 'Folheto Econômico', 'Folder 2 Dobras Verniz', 'Save the Date',
                'Cartão de Agradecimento Verniz', 'Carimbo', 'Porta Retrato em Cartão',
                'Agenda Permanente Ecológica Personalizada', 'Certificado de Garantia', 'Convite Markatto',
                'Convite de Aniversário Hot Stamping', 'Convite de Aniversário Personalizado',
                'Folder 1 Dobra Verniz', 'Agenda Personalizada 2027 Verniz', 'Calendário de Mesa Base Rígida',
                'Folder 3 Dobras Hot Stamping', 'Envelope Kraft Bolha', 'Tag Retangular',
                'Envelope de Segurança Cartão Hot Stamping', 'Cartão Postal Markatto',
                'Cardápio de Papel sem Dobra Markatto', 'Carteira de Vacinação Pet', 'Marca-Página Markatto',
                'Cartão Postal Verniz', 'Folder 2 Dobras Hot Stamping', 'Flyer Verniz',
                'Convite de Casamento Verniz', 'Blocos Adesivados Lins', 'Panfleto Econômico',
                'Save The Date Hot Stamping', 'Convite de Aniversário Verniz', 'Cartão de Visita Markatto',
                'Convite Verniz', 'Folheto Verniz', 'Cardápio de Papel Markatto', 'Folder 1 Dobra Hot Stamping',
                'Flyer Markatto', 'Capa e Contra Capa Dura para Cadernos e Agendas',
                'Envelope de Segurança Cartão Verniz', 'Cartão Duplo', 'Agenda Permanente Verniz',
                'Save The Date Markatto', 'Blocos de Notas Adesivas Cooper com Caderno',
                'Caderneta com Capa em Couro Sintético', 'Cartão Vale Presente Verniz',
                'Cartaz Splash Personalizado', 'Save The Date Verniz', 'Cardápio Redondo',
                'Papel para Scrapbook', 'Calendário de Parede Básico Verniz', 'Papel para Scrapbook Hot Stamping',
                'Papel para Scrapbook Verniz', 'Cartão de Visita Eleitoral', 'Ventarola Eleitoral',
                'Folder 1 Dobra Eleitoral', 'Cartaz Eleitoral', 'Photocard Personalizado',
            ],
        ],

        'adesivos-rotulos-etiquetas' => [
            'nome'      => 'Adesivos, Rótulos e Etiquetas',
            'descricao' => 'Autocolantes, rótulos e etiquetas em papel, vinil e BOPP.',
            'fotos'     => ['1560343090-f0409e92791a', '1626785774573-4b799315345d', '1607083206968-13611e3d76db', '1598488035139-bdbb2231ce04'],
            'produtos'  => [
                'Adesivos Redondos', 'Adesivo Retangular', 'Adesivos Personalizados', 'Rótulos Personalizados',
                'Adesivo Quadrado', 'Cartela de Adesivos', 'Rótulo Retangular', 'Lacres de Segurança',
                'Etiquetas Personalizadas', 'Adesivo Para Fechar Sacola', 'Adesivos com Corte Especial',
                'Rótulo para Garrafa de Vinho', 'Rótulo para Garrafa de Cerveja', 'Adesivo Oval',
                'Rótulo para Garrafa Plástica', 'Rótulo para Garrafa de Suco', 'Rótulo para Shampoo',
                'Rótulo para Pote de Creme', 'Adesivo Sticker Vinil', 'Adesivo de Parede',
                'Adesivos Redondos Hot Stamping', 'Adesivos Grandes', 'Adesivo Sticker Personalizado',
                'Adesivo Retangular Hot Stamping', 'Pragão Adesivo', 'Etiqueta Retangular', 'Pôster Adesivo',
                'Rótulo Econômico', 'Adesivos Personalizados Hot Stamping', 'Rótulo Frasco Personalizado',
                'Adesivo para Vidro', 'Adesivo de Piso', 'Rótulo para Latas Personalizado',
                'Adesivo de Geladeira', 'Adesivo Econômico', 'Etiqueta Redonda',
                'Etiqueta BOPP para Tempero Personalizada', 'Papel de Parede Personalizado',
                'Rótulos Personalizados Hot Stamping', 'Adesivo Quadrado Hot Stamping', 'Adesivo de Notebook',
                'Adesivo para Carro', 'Adesivo para Fechar Sacola Hot Stamping', 'Etiqueta com Corte Especial',
                'Adesivo Perfurado Personalizado', 'Rótulo Pote de Gel Personalizado',
                'Adesivo Para Fechar Sacola Verniz', 'Adesivo Premium',
                'Rótulos com Cantos Arredondados Personalizados', 'Etiquetas Hot Stamping',
                'Adesivos Redondos Verniz', 'Rótulo para Garrafa de Vinho Hot Stamping', 'Etiqueta Quadrada',
                'Adesivo Retangular Verniz', 'Rótulo Bisnaga Personalizado',
                'Etiqueta de Papel Manuscrito para Tempero', 'Adesivos com Cantos Arredondados Personalizados',
                'Adesivos Personalizados Verniz', 'Rótulo com Corte Especial',
                'Adesivo de Geladeira com Corte Especial', 'Rótulo para Garrafa de Vinho Verniz',
                'Rótulo Gargalo de Garrafa Personalizado', 'Adesivo para Tapume Personalizado',
                'Etiqueta de Preço', 'Rótulos Personalizados Verniz', 'Adesivo de Piso com Corte Especial',
                'Adesivo Quadrado Verniz', 'Adesivo de Cartão de Crédito',
                'Etiquetas com Cantos Arredondados Personalizadas', 'Rótulo Premium',
                'Pôster Adesivo com Corte Especial', 'Rótulo para Garrafa de Cerveja Verniz',
            ],
        ],

        'flyers-panfletos-folders' => [
            'nome'      => 'Flyers, Panfletos e Folders',
            'descricao' => 'Flyers, folhetos e folders dobrados para divulgar a sua campanha.',
            'fotos'     => ['1493655161922-ef98929de9d8', '1572044162444-ad60f128bdea', '1531973576160-7125cd663d86', '1503694978374-8a2fa686963a'],
            'produtos'  => [
                'Flyer', 'Folder 1 Dobra', 'Folder 2 Dobras', 'Panfleto', 'Folheto', 'Flyer Hot Stamping',
                'Flyer Premium', 'Folder 3 Dobras', 'Filipeta', 'Folder 4 Dobras', 'Folder 1 Dobra Econômico',
                'Folder 2 Dobras Econômico', 'Manual de Padrinhos', 'Folheto Econômico', 'Folder 2 Dobras Verniz',
                'Mapa Guia Dobrável', 'Folder 1 Dobra Verniz', 'Folder 3 Dobras Hot Stamping',
                'Folder 2 Dobras Hot Stamping', 'Flyer Verniz', 'Folder 2 Dobras Markatto', 'Panfleto Econômico',
                'Folheto Verniz', 'Folder 1 Dobra Hot Stamping',
            ],
        ],

        'embalagens-sacolas' => [
            'nome'      => 'Embalagens e Sacolas',
            'descricao' => 'Caixas, sacolas e embalagens personalizadas para loja, envio e delivery.',
            'fotos'     => ['1607166452427-7e4477079cb9', '1589365278144-c9e705f843ba', '1595246140625-573b715d11dc', '1553413077-190dd305871c'],
            'produtos'  => [
                'Embalagem para Correios', 'Cinta para Embalagem de Transporte', 'Embalagem para Caneca',
                'Embalagem para Transporte com Impressão Interna', 'Embalagem Basculante',
                'Cinta para Embalagem Basculante', 'Sacola de Papel Teepee', 'Cartão de Agradecimento Personalizado',
                'Tag Hot Stamping', 'Embalagem Sacola', 'Embalagem Tampa e Fundo',
                'Cinta para Embalagem Tampa e Fundo', 'Embalagem Gaveta', 'Embalagem Padrão',
                'Sacola de Papel Personalizada', 'Adesivo Para Fechar Sacola', 'Saco de Papel Kraft',
                'Sacola Plástica Personalizada', 'Embalagem para Panetone', 'Cartela para Bijuteria',
                'Embalagem para Vinho', 'Sacola de Papel Teepee para Garrafa', 'Embalagem Display',
                'Papel Embrulho para Presente', 'Caixa Maleta com Alça Personalizada', 'Embalagem com Alça',
                'Embalagem para Correios Hot Stamping', 'Cinta para Marmita', 'Embalagem Maleta',
                'Embalagem para Cerveja', 'Embalagem para Doces e Salgados', 'Solapa', 'Embalagem Hexagonal',
                'Sacola em Algodão Reciclado Personalizada', 'Embalagem para Combos', 'Caixinha Expositora',
                'Embalagem Explosão', 'Envelope de Segurança Plástico', 'Tag para Roupas',
                'Embalagem com Alça para Panetone', 'Cinta para Bolo', 'Tag Verniz',
                'Embalagem Almofada Bijuteria', 'Embalagem para Ovo de Colher', 'Tag para Ovo de Páscoa',
                'Bloco de Rascunho Cubo com Embalagem Personalizada', 'Sacola Térmica',
                'Saco Stand UP Pouch com Adesivo', 'Embalagem Milk Personalizado',
                'Embalagem Bolsinha Personalizado', 'Embalagem Gaveta Hot Stamping',
                'Sacola de Papel Teepee Hot Stamping', 'Embalagem Bandeja', 'Embalagem Almofada',
                'Sacola de Papel Teepee Verniz', 'Embalagem Delivery de Comida',
                'Embalagem Batata Frita Personalizado', 'Embalagem para Hambúrguer', 'Tag Markatto',
                'Embalagem para Correios Verniz', 'Embalagem Cesta', 'Embalagem Tampa e Fundo Hot Stamping',
                'Sacola com Adesivo', 'Sacola em TNT Laminado', 'Embalagem Chanfrada para Panetone',
                'Embalagem Gaveta Verniz', 'Embalagem Basculante Hot Stamping',
                'Embalagem Triangular Personalizado', 'Embalagem Transporte Impressão Interna e Externa',
                'Embalagem Cone', 'Embalagem com Impressão Interna em Verniz', 'Embalagem Sacola Hot Stamping',
                'Embalagem para Transporte Retornável', 'Embalagem para Doces Personalizado', 'Sacola de TNT',
                'Envelope Kraft Bolha', 'Embalagem Transporte Impressão Interna Hot Stamp',
                'Embalagem Kit Lanche', 'Embalagem para Frituras Personalizado',
                'Embalagem para Fatia de Pizza', 'Embalagem Padrão Verniz',
                'Adesivo para Fechar Sacola Hot Stamping', 'Embalagem Sacola Markatto',
                'Embalagem de Transporte Grande', 'Embalagem Basculante Verniz',
                'Embalagem Tampa e Fundo Verniz', 'Embalagem Gaveta Markatto',
                'Adesivo Para Fechar Sacola Verniz', 'Embalagem Sacola Verniz',
                'Embalagem Pirâmide Personalizado', 'Cinta para Pote de Sorvete Personalizado',
                'Embalagem Tampa e Fundo Markatto', 'Sacola para Garrafa Personalizada', 'Embalagem Cachepot',
                'Sacola Térmica Flexível Personalizada', 'Embalagem Padrão Hot Stamping',
                'Embalagem Almofada Bijuteria Markatto', 'Embalagem Mini Panetone',
                'Embalagem para Correios Markatto', 'Gargaleira Personalizado', 'Sacola de TNT Palmas',
                'Cartela para Bijuteria Markatto', 'Embalagem Cesta Páscoa', 'Embalagem para Mini Envio',
            ],
        ],

        'brindes-presentes-decoracao' => [
            'nome'      => 'Brindes, Presentes e Decoração',
            'descricao' => 'Canecas, canetas, ecobags, squeezes e brindes corporativos personalizados.',
            'fotos'     => ['1514228742587-6b1558fcca3d', '1523381210434-271e8be1f52b', '1571781926291-c477ebfd024b', '1516961642265-531546e84af2'],
            'produtos'  => [
                'Caneca Personalizada', 'Ecobag Algodão Natural', 'Botton Personalizado', 'Caderno Personalizado',
                'Mouse Pad Personalizado', 'Lata de Metal', 'Ecobag Personalizada', 'Caneta Plástica Básica',
                'Caderneta Pequena', 'Caneta Metal Classic', 'Caderneta Grande', 'Caneta Plástica Color',
                'Imã de Geladeira', 'Caderneta Capa Impressa', 'Mochila Saco', 'Caneta Slim Touch',
                'Squeeze Alumínio Tampa em Bambu', 'Mouse Pad Gamer Personalizado', 'Squeeze Metal Premium',
                'Chaveiro Alumínio Abridor', 'Caneca Preta Personalizada', 'Caneca Grande 440 ml Personalizada',
                'Squeeze Acrílico Transparente Personalizado', 'Óculos de Sol Personalizado', 'Caderno com Caneta',
                'Squeeze Metal Deluxe', 'Mochila Saco em Algodão Reciclado', 'Botton Chaveiro Dupla Face',
                'Squeeze Metal Shawn', 'Lápis Personalizado', 'Bolacha de Chopp', 'Porta Copos',
                'Caneta Plástica Touch com Suporte para Celular', 'Kit Viagem Personalizado',
                'Caneta de Metal Marieta Personalizada', 'Conjunto para Vinho em Metal Personalizado',
                'Caneca Cônica Personalizada', 'Squeeze Alumínio Rio Personalizado', 'Capacho Personalizado',
                'Squeeze Plástico Fumê Personalizado', 'Squeeze Vidro Borossilicato Personalizado',
                'Squeeze Metal Tampa Inox', 'Régua', 'Régua de Papel', 'Caneta Soft Personalizada',
                'Copo Térmico 400 ml', 'Kit Churrasco Cubat Personalizado', 'Kit Churrasco Durand Personalizado',
                'Porta Lata Personalizado', 'Tábua de servir de bambu', 'Necessaire',
                'Squeeze Metal Moderno Personalizado', 'Mouse Pad Redondo Personalizado',
                'Toalha de Praia com Ecobag', 'Sacola Térmica', 'Caderno de Desenho Capa Impressa',
                'Caderneta com Caneta Personalizado', 'Protetor de Webcam', 'Bolacha de Chopp em Neoprene',
                'Caneta Plástica Escolar', 'Copo para Viagem Personalizado 380ml', 'Cooler Personalizado',
                'Caneta Ecológica Personalizada', 'Guarda-Chuva Cabo Madeira Patti',
                'Caneta em Bambu Personalizada', 'Squeeze Térmico Buffon Personalizado', 'Balões Personalizados',
                'Caneta Alumínio Touch Personalizada', 'Cartão Vale Presente Personalizado',
                'Cartão Vale Presente Hot Stamping', 'Squeeze Térmico', 'Squeeze Térmico Rossi',
                'Caneta Plástica Stick', 'Agenda Permanente Hot Stamping', 'Botton Ímã',
                'Squeeze Garrafa de Vidro com Tampa de Bambu', 'Copo para Viagem em Fibra de Bambu 450ml',
                'Toalha de Mesa', 'Chaveiro Metal Básico', 'Caneta Metal Touch Script Personalizada',
                'Ecobag Algodão com Alça Cortiça Personalizada', 'Caneca de Chopp em Vidro Personalizada',
                'Caneta de Alumínio Classic Soft Premium', 'Guarda-Chuva Dobrável Tigot Personalizado',
                'Carregador Portátil Slim Personalizado', 'Caneca de Alumínio',
                'Tirante para Caneca Personalizado', 'Caneta Plástica Cristal', 'Bolsa Térmica',
                'Caneta em Bambu Beal Personalizado', 'Agenda Personalizada 2027 Hot Stamping',
                'Caneta Metal Olaf Soft', 'Lixeira Carro Personalizado', 'Tapete Automotivo Personalizado',
                'Caneta Plástica Sally', 'Porta Celular de Mesa Personalizado',
                'Espelho de Maquiagem Redondo Personalizado', 'Mochila Básica',
                'Porta Cartões para Celular Personalizado', 'Faixa de Gôndola Personalizada',
                'Bolinha Anti Stress', 'Squeeze em Vidro Tampa em PP Personalizado', 'Copo Twister com Canudo',
                'Necessaire Aruba Personalizada', 'Necessaire Annie Personalizada', 'Squeeze Lemon em Alumínio',
                'Mochila para Notebook 14', 'Porta Retrato em Cartão',
                'Caneta Plástica Personalizada Milu Frost', 'Caneta de Metal Deluxe Personalizada',
                'Caneta Metal Alva Roller Personalizada', 'Squeeze Plástico Enders Personalizado',
                'Mochila Notebook 15,6', 'Saca-rolhas Personalizado', 'Caneta Metal Clare Personalizada',
                'Caneta Metal Simple', 'Chinelo Personalizado', 'Bolsa Térmica de 3 Litros Personalizada',
                'Copo Térmico com Tampa Personalizável', 'Mochila Notebook Birmingham 15,6 Personalizada',
                'Mochila Notebook 15" Personalizada', 'Toalha Esportiva em Microfibra Personalizada', 'Pantufa',
                'Chaveiro Alumínio Abridor Garrafa', 'Conjunto para Vinho Syrah Personalizado',
                'Copo Térmico com Alça Joyner', 'Necessaire Millie Personalizada',
                'Caneca para Viagem Personalizada', 'Copo para Viagem em Fibra de Bambu e PP de 450ml',
                'Estojo Simples Personalizado', 'Calendário de Parede Básico Hot Stamping',
                'Marmita em Fibra de Bambu Personalizada', 'Bola de Futebol', 'Chaveiro Botton Personalizado',
                'Caneta Metal Lando Roller Personalizada', 'Squeeze Esportivo PETG Personalizado',
                'Bolsa Esportiva Personalizada', 'Mala para Viagem Bago', 'Mochila Casual',
                'Chaveiro Abridor Clane', 'Porta Cartões para Celular em Silicone',
                'Almofada de Pescoço Personalizada', 'Máscara para Dormir Personalizado',
                'Manta Polar Personalizada', 'Bolsa Esportiva Hexa', 'Mouse sem Fio Reciclado',
                'Caixa de Som em Bambu Personalizada', 'Azulejo', 'Pingente Pet Personalizado',
                'Kit Cata Caca Personalizado', 'Copo Térmico Personalizado', 'Copo Térmico sem Tampa Personalizado',
                'Necessaire Willis Personalizada', 'Necessaire Loren Personalizada',
                'Chaveiro Metal Deluxe Personalizado', 'Porta Comprimidos 3 Divisórias',
                'Mochila Notebook Bangkok 15,6 Personalizada', 'Carregador Portátil Promo Personalizado',
                'Squeeze Alumínio Reciclado Personalizado', 'Marmita Hermética Personalizada',
                'Mochila Esportiva Básica', 'Blocos Adesivados Lins', 'Botton Abridor Personalizado',
                'Botton Espelho Personalizado', 'Tapete Personalizado', 'Estojo Personalizado para Lápis',
                'Fone de Ouvido com Microfone Personalizado', 'Chaveiro Metal Tag Personalizado',
                'Squeeze Plástico com Toalha Esportiva', 'Porta Copo com Abridor Integrado', 'Ecobag Reciclada',
                'Botton Espelho Chaveiro', 'Borracha Personalizada', 'Xícara de Vidro',
                'Tapete de Papel Personalizado', 'Caneta Metal Wass', 'Manga Refrigeradora Personalizada',
                'Mochila para Notebook 17"', 'Viseira de Papel', 'Viseira Neoprene',
                'Squeeze Alumínio com Tampa PP Personalizado', 'Caixa de Som com Microfone Personalizada',
                'Lápis de Madeira', 'Caneta Ecológica Masai', 'Bolsa Esportiva Bago', 'Caneta Milink',
                'Caneta Plástica Amy', 'Avental Personalizado', 'Lápis de Resina',
                'Caneta Metal Lando Personalizado', 'Carregador Portátil Indução Personalizado',
                'Squeeze Plástico Básico', 'Porta Comprimidos', 'Fone de Ouvido Wireless Personalizado',
                'Suporte de Dedo para Celular', 'Fone de Ouvido Intra Auricular',
                'Conjunto de Caneta e Lapiseira em Bambu', 'Display de Mesa com Calendário Verniz',
                'Mochila Trolley Notebook 15,6 Personalizada', 'Chinelo Personalizado Premium',
                'Caneta Metal Touch Shanghai Personalizada', 'Copo Térmico Joyner', 'Casinha para Gato',
                'Copo in Mold', 'Kit Lápis de Cor', 'Caneta Plástica Caribe',
                'Blocos de Notas Adesivas Cooper com Caderno', 'Mochila Esportiva Casual',
                'Caderneta com Capa em Couro Sintético', 'Cartão Vale Presente Verniz',
                'Display de Mesa com Calendário Hot Stamping', 'Porta Celular Personalizado para Carro',
                'Mouse sem Fio Personalizado', 'Adesivo de Cartão de Crédito',
                'Toalha Esportiva em Pet Personalizado', 'Chaveiro em Couro Sintético e Metal',
                'Caixa de Som com Microfone em Bambu', 'Chaveiro em Bambu Personalizado',
                'Mala para Viagem Personalizada', 'Squeeze Plástico Executivo Personalizado',
                'Cortador de Pizza', 'Caneta em Alumínio Reciclado', 'Porta Cartões', 'Garrafa Térmica',
                'Chaveiro Metal Premium', 'Squeeze de Vidro com Capa Neoprene',
                'Fone de Ouvido Ajustável Personalizado', 'Bola de Vôlei', 'Caneta Metal Personalizada Deli',
                'Descanso de Panela Personalizado', 'Estojo Zip Zap Personalizado',
                'Chapéu Bucket Personalizado', 'Ecobag Burgos', 'Baralho com Caixa Personalizado',
                'Pasta Zip Zap Personalizada', 'Kit Vinho Personalizado', 'Canivete Personalizado',
                'Carregador para Carro Personalizado', 'Photocard Personalizado',
            ],
        ],

        'agendas-calendarios' => [
            'nome'      => 'Agendas e Calendários',
            'descricao' => 'Agendas, planners e calendários de mesa, parede e bolso.',
            'fotos'     => ['1506784983877-45594efa4cbe', '1435527173128-983b87201f4d', '1484480974693-6ca0a78fb36b', '1517842645767-c639042777db'],
            'produtos'  => [
                'Calendário de Mesa 2027', 'Agenda Personalizada 2027', 'Agenda Permanente',
                'Mini Calendário de Mesa 2027', 'Calendário de Parede Básico 2027', 'Planner Semanal',
                'Calendário de Parede Premium 2027', 'Display de Mesa com Calendário Personalizado 2027',
                'Agenda Permanente Hot Stamping', 'Calendário de Mesa Premium 2027',
                'Agenda Personalizada 2027 Hot Stamping', 'Agenda Permanente Ecológica Personalizada',
                'Agenda Personalizada 2027 Verniz', 'Calendário de Parede Básico Hot Stamping',
                'Calendário de Mesa Base Rígida', 'Calendário de Bolso 2027',
            ],
        ],

        'banners-faixas-placas' => [
            'nome'      => 'Banners, Faixas e Placas',
            'descricao' => 'Comunicação de grande formato: banners, roll-ups, faixas e placas.',
            'fotos'     => ['1620799140408-edc6dcb6d633', '1558693168-c370615b54e0', '1567443024551-f3e3cc2be870', '1561070791-2526d30994b5'],
            'produtos'  => [
                'Banner Personalizado', 'Placa Personalizada', 'Banner Roll-Up', 'Faixa Personalizada', 'Móbile',
                'Móbile Promocional', 'Placa com Corte Especial', 'Banner-X', 'Backdrop Retrátil',
                'Bandeira Personalizada', 'Faixa de Gôndola Personalizada', 'Bandeirola', 'Flâmula Personalizado',
                'Banner com Moldura', 'Lona Backlight Personalizado', 'Cobre Placa Personalizado',
                'Bandeira para Carro Personalizado', 'Cavalete Personalizado', 'Mini Banner',
                'Placa Moldura para Fotos', 'Placa Pirulito', 'Aviso de Porta com Corte Especial',
                'Móbile Tipo U', 'Móbile com Corte Especial',
            ],
        ],

        'catalogos-livros-revistas' => [
            'nome'      => 'Catálogos, Livros e Revistas',
            'descricao' => 'Catálogos, livros, revistas e apostilas com acabamento profissional.',
            'fotos'     => ['1544716278-ca5e3f4abd8c', '1512820790803-83ca734da794', '1495446815901-a7297e633e8d', '1476275466078-4007374efbbe'],
            'produtos'  => [
                'Catálogo Personalizado', 'Livreto Personalizado', 'Livro', 'Revista', 'Livro Hot Stamping',
                'Brochura', 'Impressão de Apostilas', 'Apostila Capa Impressa', 'Fotolivro',
                'Revista em Quadrinhos', 'Catálogo Verniz', 'Catálogo Hot Stamping', 'Livreto Econômico',
                'Livro Verniz', 'Revista Hot Stamping', 'Revista Verniz',
            ],
        ],
    ];
}

/**
 * Ordem de prioridade para resolver produtos repetidos em várias categorias:
 * o produto fica na categoria mais específica em que aparece.
 *
 * @return string[]
 */
function catalogo_prioridade(): array
{
    return [
        'agendas-calendarios',
        'catalogos-livros-revistas',
        'banners-faixas-placas',
        'flyers-panfletos-folders',
        'adesivos-rotulos-etiquetas',
        'embalagens-sacolas',
        'brindes-presentes-decoracao',
        'papelaria-personalizada',
    ];
}
